apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-server
spec:
  selector:
    app: k8s-dashboard-server
  ports:
    - port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-dashboard-server-config
data:
  config.yaml: |
    server:
      port: 8080
    k8s:
      host: "https://192.168.48.136:6443"
      token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjU2RDJXZS1lWmVtR2RKWlpwMGpKY2MzSzVvNVVPajkwNDhDM3Fkc0psWW8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrOHMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYWRtaW4tdXNlci10b2tlbi1ubDcydyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbi11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTFlZDU1MTYtMjdmMi00OWRlLWE5MjUtOTUzMTViZTNlMTk0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Oms4czphZG1pbi11c2VyIn0.puPkl1tDMRXmesQTDzaxbQ5n-j_OrRI5-33NHZRzeOAG0-QKxRYgxOXjVRuwTFMETZvalpn9gwGZOc2kRro_EZUEfuTSfnLxZ-iLAdDgH-PErLb9G6YmOzglntv6a0POZ_3Xw2mW6tPdEpuH7MBb9nm7YFh-JJC8xRVMXNI6IWlVa0HYTqWmWgteXjZpDUku0LyEUx0h7i4uyCfhKdfnu0LHpoNN5FiceLcVm4YU6gB2hagfUKKmGN7_GwUqzyJp8AdfPhZ9SNYjgMnO1hkz4QdjPbD5R0uF2LCeRygHh_WpKyTdhVG_HQALHUYOjIMPeismM6XMFTM1wTaJHQucLg"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-server
  labels:
    app: k8s-dashboard-server
  annotations:
    lastUpdate: {{now}}
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-dashboard-server
      labels:
        app: k8s-dashboard-server
    spec:
      containers:
        - name: k8s-dashboard-server
          image: registry.cn-hangzhou.aliyuncs.com/zhqn/k8s-dashboard-server:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /product/config
              name: server-config
      restartPolicy: Always
      volumes:
        - name: server-config
          configMap:
            name: k8s-dashboard-server-config
  selector:
    matchLabels:
      app: k8s-dashboard-server

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-web
spec:
  selector:
    app: k8s-dashboard-web
  ports:
    - port: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-web
  labels:
    app: k8s-dashboard-web
  annotations:
    lastUpdate: {{now}}
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-dashboard-web
      labels:
        app: k8s-dashboard-web
    spec:
      containers:
        - name: k8s-dashboard-web
          image: registry.cn-hangzhou.aliyuncs.com/zhqn/k8s-dashboard-web:1.0.0
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: k8s-dashboard-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-dashboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: k8s-dashboard-web
                port:
                  number: 80
            pathType: Prefix
            path: /(.*)
          - backend:
              service:
                name: k8s-dashboard-server
                port:
                  number: 8080
            pathType: Prefix
            path: /api/(.*)




